In [2]:
# 1
import numpy as np

a = np.arange(0, 26).reshape((2,-1))
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24 25]]


In [3]:
# 2
a_transposed = a.T
a_reshaped = a.reshape((13,-1))

print(a_transposed)
print(a_reshaped)

# reshape는 각 element들이 메모리상 위치하는 순서는 유지한 채로 array의 모양만 바꾸고,
# transpose는 행과 열을 서로 교환하여 실제 위치가 바뀐다.

[[ 0 13]
 [ 1 14]
 [ 2 15]
 [ 3 16]
 [ 4 17]
 [ 5 18]
 [ 6 19]
 [ 7 20]
 [ 8 21]
 [ 9 22]
 [10 23]
 [11 24]
 [12 25]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]]


In [4]:
# 3
a = np.arange(0, 27).reshape((3,3,-1))
a[:, 1, 1] = 999
print(a)

[[[  0   1   2]
  [  3 999   5]
  [  6   7   8]]

 [[  9  10  11]
  [ 12 999  14]
  [ 15  16  17]]

 [[ 18  19  20]
  [ 21 999  23]
  [ 24  25  26]]]


In [5]:
# 4
z = np.zeros((4, 4)) + 10.
print(z)

o = np.ones((4, 4)) * 10.
print(o)

f = np.full((4, 4), 10.)
print(f)

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [6]:
# 5
a = np.arange(0, 20).reshape((5,-1))
print(a)

b = np.full_like(a, -999)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[-999 -999 -999 -999]
 [-999 -999 -999 -999]
 [-999 -999 -999 -999]
 [-999 -999 -999 -999]
 [-999 -999 -999 -999]]


In [7]:
# 6
a = np.arange(0, 20).reshape((5,-1))
b = np.full_like(a, -999)

c = np.hstack((a, b))
print(c)

[[   0    1    2    3 -999 -999 -999 -999]
 [   4    5    6    7 -999 -999 -999 -999]
 [   8    9   10   11 -999 -999 -999 -999]
 [  12   13   14   15 -999 -999 -999 -999]
 [  16   17   18   19 -999 -999 -999 -999]]


In [8]:
# 7
# np.exp를 적용하면 리스트인 data를 n-d array로 바꿔서 병렬로 exp 연산을 처리할 것 같다.
# math.exp는 리스트를 argument로 받지 않기 때문에 오류가 날 것이다.

In [9]:
# 8
a = np.random.rand(4)
print(a)

b = np.random.randn(12).reshape((4,-1))
print(b)

c = np.full((1, 4), 42.)
print(c)

[0.77649639 0.69763259 0.81050686 0.52600542]
[[ 0.08119663  0.53571647  0.40660916]
 [ 1.06285749 -0.42340544  0.60466876]
 [-0.20432109 -1.22176396 -0.41967169]
 [ 0.48735519  2.02212702  0.48798027]]
[[42. 42. 42. 42.]]


In [10]:
# 9
print(f'a={a.shape}')
print(f'b={b.shape}')
print(f'c={c.shape}')

# a는 b와 연산이 불가하고, c를 transpose하면 b와 연산이 가능하다.
# elementwise 연산을 할 때 shape이 맞지 않는 경우 broadcasting이 일어나는데,
# broadcasting이 가능한 조건이, 서로 크기가 맞는 axis가 있어야 한다는 것이다. (튜플 뒤에서부터 확인.)
# c를 transpose하면 그 shape은 (4, 1)이 되고, 여러 행에 한번에 연산이 가능해진다.

a=(4,)
b=(4, 3)
c=(1, 4)


In [11]:
# 10
# axis2를 일치하게 하려면 b를 transpose시키는 방법밖에 없었다.
print(f'b + a = {b.T + a}')
# 9번에서 설명한 이유로 c를 Transpose시켰다.
# 그러나 b.T + c도 가능하다. 결과의 shape은 각각 (4, 3), (3, 4)로 다르다.
print(f'b + c = {b + c.T}')

b + a = [[ 0.85769303  1.76049008  0.60618578  1.01336061]
 [ 1.31221287  0.27422715 -0.41125709  2.54813244]
 [ 1.18310555  1.30230134  0.39083517  1.01398569]]
b + c = [[42.08119663 42.53571647 42.40660916]
 [43.06285749 41.57659456 42.60466876]
 [41.79567891 40.77823604 41.58032831]
 [42.48735519 44.02212702 42.48798027]]


In [12]:
# 11
a = np.linspace(0, 1, 11)
print(a)

b = np.arange(0, 1.1, 0.1)
print(b)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [13]:
# 12
matrix = np.ones((5, 5)) * np.arange(-2, 3)
print(matrix)

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


In [14]:
# 13
rng = np.random.default_rng(seed=10)
matrix = matrix - rng.integers(-5, 6, size=(5, 5))
print(matrix)

[[-5. -6.  3.  4. -1.]
 [-6. -1.  4. -3.  2.]
 [ 2.  3.  1. -1.  3.]
 [-6.  4.  1.  1. -3.]
 [ 1. -5.  5.  3. -1.]]


In [15]:
# 14
matrix[matrix < 0] = 0
print(matrix)

[[0. 0. 3. 4. 0.]
 [0. 0. 4. 0. 2.]
 [2. 3. 1. 0. 3.]
 [0. 4. 1. 1. 0.]
 [1. 0. 5. 3. 0.]]


In [16]:
# 15
p = np.arange(1, 6).reshape((1, 5))
print(np.tile(p, 4).reshape((2, -1)))

[[1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]]


In [17]:
# 16
p = np.arange(1, 7).reshape((1, 2, -1))

print(np.repeat(p, 2, axis=0))
print()
print(np.repeat(p, 2, axis=1))
print()
print(np.repeat(p, 2, axis=2))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

[[[1 2 3]
  [1 2 3]
  [4 5 6]
  [4 5 6]]]

[[[1 1 2 2 3 3]
  [4 4 5 5 6 6]]]


In [18]:
# 17
a = np.array([84, 91, 13, 65, 8, 31, 48, 4])
print(f'max value index : {a.argmax()}')
print(f'min value index : {a.argmin()}')

max value index : 1
min value index : 7


In [19]:
# 18
a = np.random.randint(-100, 101, 10000000)
print(f'min value : {a.min()}')
print(f'max value : {a.max()}')
print(f'mean value : {a.mean()}')
print(f'standard deviation value : {a.std()}')

min value : -100
max value : 100
mean value : 0.0061942
standard deviation value : 58.02427130806458


In [20]:
# 19
a = np.random.normal(5, 3, 10000000)
print(f'min value : {a.min()}')
print(f'max value : {a.max()}')
print(f'mean value : {a.mean()}')
print(f'standard deviation value : {a.std()}')

min value : -9.273169087034429
max value : 20.766149429711707
mean value : 4.9988134230556405
standard deviation value : 2.999125208871624


In [38]:
# 20
a = np.array([[4, 1],
     [2, 4]])
b = np.array([[5, 6],
     [1, 8]])

print((a @ b) @ (b @ a))

[[1312 1665]
 [1328 1858]]


In [ ]:
# 21
c = np.array([[1, 2],
     [8, 4],
     [3, 9]])

# a.shape = (2, 2)
# b.shape(2, 2)
# c.shape = (3, 2)
# 2x2 행렬과 3x2 행렬의 곱셈은 불가능하다. mxn, rxp 행렬의 곱셈은 n=r일 때라야 가능하다.
# [3x2] [2x2] 는 가능하다.
print((c @ a) + (c @ b))

[[ 15  31]
 [ 84 104]
 [ 54 129]]


In [47]:
# 22
k = np.ones((3, 4)) * np.linspace(-1, 2.5, 4)
print(k)
print(f'올림 : {np.ceil(k)}')
print(f'내림 : {np.floor(k)}')
print(f'반올림 : {np.round(k)}')

[[-1.          0.16666667  1.33333333  2.5       ]
 [-1.          0.16666667  1.33333333  2.5       ]
 [-1.          0.16666667  1.33333333  2.5       ]]
올림 : [[-1.  1.  2.  3.]
 [-1.  1.  2.  3.]
 [-1.  1.  2.  3.]]
내림 : [[-1.  0.  1.  2.]
 [-1.  0.  1.  2.]
 [-1.  0.  1.  2.]]
반올림 : [[-1.  0.  1.  2.]
 [-1.  0.  1.  2.]
 [-1.  0.  1.  2.]]


In [ ]:
# 23
# np.sum은 모든 요소의 합을 반환한다.
print(np.sum(k))
# np.cumsum은 각 위치에서의 누적합을 반환한다.
print(np.cumsum(k))

9.0
[-1.         -0.83333333  0.5         3.          2.          2.16666667
  3.5         6.          5.          5.16666667  6.5         9.        ]


In [58]:
# 24
random_value = np.array([13, 20, 28, 38, 14, 41, 0, 37])
a = random_value[np.newaxis, :].T
print(a)

[[13]
 [20]
 [28]
 [38]
 [14]
 [41]
 [ 0]
 [37]]


In [81]:
# 25
print(np.sort(a, 0))
print(a[np.argsort(a, 0)[:, 0]])

[[ 0]
 [13]
 [14]
 [20]
 [28]
 [37]
 [38]
 [41]]
[[ 0]
 [13]
 [14]
 [20]
 [28]
 [37]
 [38]
 [41]]
