# NumPy
- numpy가 다루는 데이터: n-dimensional arrays로 저장된다.
- n-dimensional arrays: also called Tensors
- scalars (0D, rank 0 tensor)
- vectors (1D, rank 1 tensor)
- matrices (2d, rank 2 tensor)
- 3d and above (rank 3 tensor and above)

In [2]:
import numpy as np

In [3]:
# scalar
# rank 0 tensor
# 0D array
a = np.array(42)
print(a)
print(type(a))
print(a.ndim)
print(a.dtype) # array의 data type
print(a.shape)

42
<class 'numpy.ndarray'>
0
int64
()


In [4]:
# vector
# 1D array
# rank 1 tensor
# audio signals, sensor values, ...
a = np.array([1, 2, 3]) # list를 vector로...
print(a)
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.shape) # vector의 길이 (element #)

[1 2 3]
<class 'numpy.ndarray'>
1
int64
(3,)


In [5]:
# matrix
# 2D array
# rank 2 tensor
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.shape) # (column len, row len) axis1 길이=2, axis2 길이=3
               # 2x3

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
int64
(2, 3)


In [6]:
# 3D array
# rank 3 tensor
# matrix가 여러 개
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a)
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.shape) # 2x2x3

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3
int64
(2, 2, 3)


In [7]:
np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]])

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

# list vs ndarray

In [8]:
import time

a = list(range(10000))
b = list(range(10000, 20000))
# c = [a[i] + b[i] for i in range(10000)]

start = time.time()
for _ in range(10000):
    c = [n1 + n2 for n1, n2 in zip(a, b)]
end = time.time()
tlist = end - start
print(f'list={tlist:.6f}')
# print(c[:10])
# help(zip)

list=2.204246


In [9]:
na = np.array(a)
nb = np.array(b)

start = time.time()
# 병렬로 처리해서 빠르다.
# GPU로 한번에 여러 element 연산.
# GPU는 내부에 코어가 수만개씩 들어있다. -> 한번에 수만개씩 연산.
# CPU로만 계산해도 병렬 처리가 가능하다. -> SIMD instruction. 이를 위한 레지스터가 따로 있다.
# 근데 numpy는 GPU쓰는 건 아니고 SIMD를 쓴다.
for _ in range(10000):
    nc = na + nb
end = time.time()
tndarray = end - start
print(f'ndarray={tndarray:.6f}')
# print(nc[:10])

ndarray=0.024105


In [10]:
tlist / tndarray

91.4441411234088

## Vector
- list와 다른 점 -> 같은 종류의 데이터 타입만 들어간다.

In [11]:
a = np.zeros((4, 2), dtype=np.int32)
print(a)
print(a.shape)
print(a.dtype)

b = np.ones((4, 2), dtype=np.float32)
print(b)
print(b.shape)
print(b.dtype)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]
(4, 2)
int32
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
(4, 2)
float32


In [12]:
a = np.empty(3) # 초기화 x. 쓰레기값.
print(a)
print(a.shape)
print(a.dtype)

[-1.40444743e+306  3.18618458e-058  2.12614031e-314]
(3,)
float64


In [13]:
a = np.full((4, 2), 42, dtype=np.uint64) # 특정 값으로 초기화.
print(a)
print(a.shape)
print(a.dtype)

[[42 42]
 [42 42]
 [42 42]
 [42 42]]
(4, 2)
uint64


In [14]:
a = np.arange(0, 10, 0.1, dtype=np.float32) # python range와 비슷. 다만 데이터타입 여러가지 지원된다.
print(a)
print(a.dtype)
print(a.shape)

[0.         0.1        0.2        0.3        0.4        0.5
 0.6        0.7        0.8        0.90000004 1.         1.1
 1.2        1.3000001  1.4        1.5        1.6        1.7
 1.8000001  1.9        2.         2.1000001  2.2        2.3
 2.4        2.5        2.6000001  2.7        2.8        2.9
 3.         3.1000001  3.2        3.3        3.4        3.5
 3.6000001  3.7        3.8        3.9        4.         4.1
 4.2000003  4.3        4.4        4.5        4.6        4.7000003
 4.8        4.9        5.         5.1        5.2000003  5.3
 5.4        5.5        5.6        5.7000003  5.8        5.9
 6.         6.1        6.2000003  6.3        6.4        6.5
 6.6        6.7000003  6.8        6.9        7.         7.1
 7.2000003  7.3        7.4        7.5        7.6        7.7000003
 7.8        7.9        8.         8.1        8.2        8.3
 8.400001   8.5        8.6        8.7        8.8        8.900001
 9.         9.1        9.2        9.3        9.400001   9.5
 9.6        9.7        

In [15]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(
    start_or_stop,
    /,
    stop=None,
    step=1,
    *,
    dtype=None,
    device=None,
    like=None
)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When

# Types of Data
- structured data: table (excel, csv, etc.)
  - using pandas to handle structured data
- unstructured data: 대부분의 데이터... (image, sound, etc.)
  - multi-dimensional array
  - image: 3-d array, rank 3 tensor
  - text: 1-d array

In [16]:
a = [1, 2, 3]
[q * 2 for q in a]

[2, 4, 6]

In [17]:
a = np.array([1, 2, 3])
b = np.full_like(a, 8) # a의 shape대로..
b

array([8, 8, 8])

In [18]:
np.arange(0, 5, 0.5) # matlab: 0:0.5:4.5

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [19]:
help(np.linspace) # [a, b] 사이에 num개를 만든다
# help(np.arange)

Help on method descriptor linspace in module numpy:

linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None
)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
      

In [20]:
np.linspace(0, 10, 11) # linear space

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
# random
# help(np.random.randint)
# np.random.randint(0, 10, size=(2, 3), dtype=np.int32)
# help(np.random.uniform)
# np.random.uniform(0, 10, size=(2, 3))
# help(np.random.normal) # scale -> std dev., loc ->  평균
print(np.random.normal(0, 1, size=(10,))) # std normal dist.
print(np.random.normal(0, 0.01, size=(10,)))
print(np.random.normal(10, 0.01, size=(10,)))

[-0.16581742 -1.03123327 -1.20889855 -1.3868571   0.70861839 -0.64397825
  0.20999088  0.9024478  -0.58684469 -0.20353336]
[ 0.00777758  0.00105448 -0.00827484  0.00950497 -0.00260314 -0.00710214
 -0.00279318 -0.00956173  0.00527449 -0.00079063]
[ 9.98663022 10.00466797 10.02382384 10.00399644  9.98624615 10.00338944
  9.98903704  9.98783927  9.99083899 10.0134109 ]


In [22]:
# matlab style
# np.random.rand(2, 3) # uniform dist. shape=2x3. 옛날 코드에서 자주 쓴다.
np.random.randn(2, 3) # std normal dist. shape=2x3.

array([[0.10015117, 0.71504189, 1.69830004],
       [0.53763725, 0.56521801, 0.43239026]])

- 암호화 공부할거면 랜덤수의 퀄리티가 아주 중요해진다.

In [23]:
# 완벽한 랜덤이 아니다. 정해진 알고리즘으로 만들어내는 것.
# 실험 재현할 때 동일한 숫자가 필요할 때가 있어서 그럴 때 시드를 고정해두고 쓴다.
np.random.seed(1)

np.random.randn(2, 3)

array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ]])

In [24]:
# indexing
a = np.arange(20)
print(a)
print(a[3])
print(a[:3]) # slicing
print(a[3:7])
print(a[7:])

b = a[:5] # python은 copy인데, numpy는 아니다.
print(b)
b[0] = 100
print(a)

# view: slicing하면 그 부분으로 연결만 해준다. 주로 데이터가 아주 크기 때문에 오버헤드 줄이기 위함.

c = a.copy()
c[0] = 200 # real copy
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
3
[0 1 2]
[3 4 5 6]
[ 7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [25]:
# fancy indexing
a = np.random.randint(0, 10, size=(10,))
print(a)

# fancy indexing은 copy를 한다.
b = a[[0, 4, 2]]
b[0] = 100
print(f'a={a}')
print(f'b={b}')

[5 2 4 2 4 7 7 9 1 7]
a=[5 2 4 2 4 7 7 9 1 7]
b=[100   4   4]


In [26]:
# boolean indexing
a = np.random.uniform(-1, 1, size=(10,))
print(a)

b = a < 0
print(b)

print(a[b]) # 인덱스가 true인 부분만 가져온다.
print(a[a > 0])

c = [a < 0] # fancy indexing과 마찬가지로 copy.
c[0] = 100

a[a < 0] = 0 # 음수인 element를 0으로 바꿔준다.
print(a)

[ 0.87825558  0.55677847  0.43194103  0.60551501 -0.81439838  0.0363051
  0.7300405   0.65829381  0.65920672 -0.45390005]
[False False False False  True False False False False  True]
[-0.81439838 -0.45390005]
[0.87825558 0.55677847 0.43194103 0.60551501 0.0363051  0.7300405
 0.65829381 0.65920672]
[0.87825558 0.55677847 0.43194103 0.60551501 0.         0.0363051
 0.7300405  0.65829381 0.65920672 0.        ]


In [27]:
# operations
a = np.random.randint(1, 10, (5,))
b = np.random.randint(1, 10, (5,))

print(a)
print(b)

print(a + b)
# element-wise multiplication
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** 2)
print(a ** b)

[9 8 4 7 6]
[2 4 5 9 2]
[11 12  9 16  8]
[18 32 20 63 12]
[4.5        2.         0.8        0.77777778 3.        ]
[4 2 0 0 3]
[1 0 4 7 0]
[81 64 16 49 36]
[      81     4096     1024 40353607       36]


In [28]:
# operations: broadcasting
a = np.arange(10)
print(a)
b = a + 10 # shape이 다르기 때문에 원칙적으로는 연산 불가.
           # 10을 a의 shape과 맞춰준 다음에 각각 더한다.
           # 이런 과정을 broadcasting이라고 한다.
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [29]:
a = np.arange(1, 11)
print(a)
print(np.sin(a))
print(np.cos(a))
print(np.log(a)) # 자연로그
print(np.log10(a))
print(np.log2(a))

[ 1  2  3  4  5  6  7  8  9 10]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]


In [30]:
a = np.random.randint(0, 100, size=(10,))
print(a)

# function call style
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.std(a))
print(np.argmax(a)) # 최댓값 인덱스
print(np.argmin(a)) # 최솟값 인덱스
print()
# method
print(a.max())
print(a.min())
print(a.mean())
print(a.std())
print(a.argmax())
print(a.argmin())

[43 76 26 52 80 41 82 15 64 68]
82
15
54.7
21.986586820150144
6
7

82
15
54.7
21.986586820150144
6
7


In [31]:
# dot product
a = np.array([1, 2, 3])
b = np.array([3, 0, 1])

print(np.dot(a, b)) # 3 + 0 + 4 = 7
# 예각 -> dot > 0
# 둔각 -> dot < 0
# 직각 orthogonal -> dot = 0

print(a.dot(b))
print(b.dot(a))

print(a @ b) # @: matrix multiplication

6
6
6
6


In [42]:
# lab

a = list(range(100000))
b = list(range(100000))

na = np.array(a)
nb = np.array(b)

In [43]:
%%timeit

np.dot(na, nb)

26.7 μs ± 277 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [48]:
def dot(a, b):
    return sum([ea * eb for ea, eb in zip(a, b)])

In [51]:
%%timeit

dot(a, b)

2.57 ms ± 29.9 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [50]:
print(np.dot(na, nb))
print(dot(a, b))

333328333350000
333328333350000


In [60]:
# lab: 벡터연산
def softmax(z):
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z) # element-wise operation

logits = np.array([2.0, 1.0, -1.0])
probs = softmax(logits)
print(probs)
print(np.sum(probs))

[0.70538451 0.25949646 0.03511903]
1.0


# 2D, 3D, array (rank2(matrix), rank3 tensor)

In [66]:
a = np.random.randint(0, 20, size=(3, 4))
print(a)
print(a.shape)
print(a.ndim)

# 행 단위 이동 -> axis 0 따라 이동
# 열 단위 이동 -> axis 1 따라 이동

[[19  1  2 12]
 [ 7  2 10  0]
 [ 9 18  6  2]]
(3, 4)
2


In [87]:
# indexing
a = np.random.randint(0, 20, size=(4, 5))

print('a')
print(a)
# print(a[0, 0]) # axis0 먼저 인덱싱
# print(a[2, 3])

# print(a[:3, 2:3]) # matlab이랑 거의 똑같음

# b = a[::2, ::2] # not copy, but view
# print('b')
# print(b)

# b[0, 0] = 100
# print('a')
# print(a)

c = a[:, [0, -1]] # fancy indexing. copy
                  # 모든 행, 첫번째, 그리고 마지막 열
c[0, 0] = 100
print('c')
print(c)

print('a')
print(a)

a
[[18  8 12 16 17]
 [11  6  0 16  1]
 [18  7 14  4  0]
 [ 1 16  2  4  3]]
c
[[100  17]
 [ 11   1]
 [ 18   0]
 [  1   3]]
a
[[18  8 12 16 17]
 [11  6  0 16  1]
 [18  7 14  4  0]
 [ 1 16  2  4  3]]


In [102]:
# reshaping
a = np.arange(20) # generates a 1d array
print('a')
print(a)

b = a.reshape((4, -1)) # 하나만 쓰고 나머지는 -1 쓰면 자동으로 값을 채워줌.
                       # 이것도 view만 바꾼다.
b[1, 1] = 1000
print('b')
print(b)

print('a')
print(a)

c = a.reshape((4, -1), copy=True) # copy
c[1, 1] = 2000
print('c')
print(c)

print('a')
print(a)

a
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
b
[[   0    1    2    3    4]
 [   5 1000    7    8    9]
 [  10   11   12   13   14]
 [  15   16   17   18   19]]
a
[   0    1    2    3    4    5 1000    7    8    9   10   11   12   13
   14   15   16   17   18   19]
c
[[   0    1    2    3    4]
 [   5 2000    7    8    9]
 [  10   11   12   13   14]
 [  15   16   17   18   19]]
a
[   0    1    2    3    4    5 1000    7    8    9   10   11   12   13
   14   15   16   17   18   19]


In [127]:
a = np.arange(10)
print('a')
print(a)

# b = a[:, None] # 뒤에 axis 추가
# print('b')
# print(b)
# print(b.shape)

c = a[None, :] # 앞에 axis 추가
print('c')
print(c)
print(c.shape)

# # 2차원 공간 안에 1차원 데이터를 둔 것이라 생각하면 됨.

# d = a[np.newaxis, :, np.newaxis]
# print('d')
# print(d)
# print(d.shape)

e = c.reshape((10,))
print(e)
print(e.shape)

e = c.reshape(-1) # 강제로 1차원으로 나열해버린다. returns a view
print(e)
print(e.shape)

e = c.flatten() # returns a copy
print(e)
print(e.shape)

a
[0 1 2 3 4 5 6 7 8 9]
c
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
[0 1 2 3 4 5 6 7 8 9]
(10,)
[0 1 2 3 4 5 6 7 8 9]
(10,)
[0 1 2 3 4 5 6 7 8 9]
(10,)


In [ ]:
# transpose
a = np.arange(10).reshape((5, -1)) # 5x2
print(a)
print(a.T) # transpose. axis를 뒤바꾼다. 2x5

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [ ]:
# broadcasting
a = np.arange(12).reshape((3,-1)) # (3, 4)
print('a')
print(a)
print(a.shape)

# b = a * 10 # shape이 달라서 연산 불가. 그러나 broadcasting으로 shape을 동일하게 맞춰준다.
# print('b')
# print(b)
# print(b.shape)

# c = np.array([2, 2, 2, 2]) # (4, )
# print('c')
# print(c.shape)

# d = a * c # multiply several columns at once
# print('d')
# print(d)
# print(d.shape)

# shape를 뒤에서부터 맞춰나간다.
# (3, 4), (3, 1)
# -> axis0이 같으니 axis1(4/1) -> 4번 반복해야 함을 알 수 있음.
e = np.array([2, 2, 2]).reshape((3, -1))
print(e.shape)
f = a * e
print('f')
print(f)

# 실제로 복사가 일어나는 것이 아니라 반복하는 것.

a
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
(3, 1)
f
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [176]:
# sum(), mean(), min(), max(), argmin(), argmax()
np.random.seed(1)
a = np.random.randint(20, size=(4, 5))
print(a)

print(f'sum={a.sum()}')
print(f'mean={a.mean()}')
print(f'min={a.min()}')
print(f'max={a.max()}')

print(f'sum of each row={a.sum(axis=1)}')
print(f'sum of each col={a.sum(axis=0)}')
print(f'mean of each row={a.mean(axis=1)}')
print(f'mean of each col={a.mean(axis=0)}')

b = a.sum(axis=0)

print('b')
print(b)
print(b.shape) # axis가 1개로 줄어버렸다.

b = a.sum(axis=0, keepdims=True)
print('b')
print(b)
print(b.shape)

[[ 5 11 12  8  9]
 [11  5 15  0 16]
 [ 1 12  7 13  6]
 [18  5 18 11 10]]
sum=193
mean=9.65
min=0
max=18
sum of each row=[45 47 39 62]
sum of each col=[35 33 52 32 41]
mean of each row=[ 9.   9.4  7.8 12.4]
mean of each col=[ 8.75  8.25 13.    8.   10.25]
b
[35 33 52 32 41]
(5,)
b
[[35 33 52 32 41]]
(1, 5)


In [187]:
# sorting
a = np.random.randint(1, 20, size=(4, 5))
print('a')
print(a)

# in-place sort
a.sort(axis=0)
print('a.sort(axis=0)')
print(a)

print('b = np.sort(a, axis=0)')
b = np.sort(a, axis=0) # returns a sorted copy of the original array
print(b)

a
[[18  7 10 11 14]
 [ 7  7 17 17 19]
 [13 10  1 17 10]
 [17 16 11  5 15]]
a.sort(axis=0)
[[ 7  7  1  5 10]
 [13  7 10 11 14]
 [17 10 11 17 15]
 [18 16 17 17 19]]
b = np.sort(a, axis=0)
[[ 7  7  1  5 10]
 [13  7 10 11 14]
 [17 10 11 17 15]
 [18 16 17 17 19]]
