In [1]:
import numpy as np

In [3]:
a = np.arange(0, 26).reshape((2, 13))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [9]:
b = a.T
c = a.reshape((13, 2))

print(b)
b[0,0] = 42

c[0,1] = 42
print(c)
print(a)

[[42 13]
 [42 14]
 [ 2 15]
 [ 3 16]
 [ 4 17]
 [ 5 18]
 [ 6 19]
 [ 7 20]
 [ 8 21]
 [ 9 22]
 [10 23]
 [11 24]
 [12 25]]
[[42 42]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]]
[[42 42  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24 25]]


In [11]:
a = np.arange(0, 27).reshape((3, 3, 3))
a[:, 1, 1] = 999
print(a)

[[[  0   1   2]
  [  3 999   5]
  [  6   7   8]]

 [[  9  10  11]
  [ 12 999  14]
  [ 15  16  17]]

 [[ 18  19  20]
  [ 21 999  23]
  [ 24  25  26]]]


In [17]:
a = np.zeros((4, 4)) + 10
b = np.ones((4, 4)) * 10
# c = np.full((4, 4), 10, dtype=np.float64)
c = np.full((4, 4), 10.)

print(a)
print(b)
print(c)

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [88]:
a = np.arange(0, 20).reshape((5, -1))
b = np.full_like(a, -999)

c = np.vstack((a, b))
b[0,0] = 42
print(c)

[[   0    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]
 [  16   17   18   19]
 [-999 -999 -999 -999]
 [-999 -999 -999 -999]
 [-999 -999 -999 -999]
 [-999 -999 -999 -999]
 [-999 -999 -999 -999]]


In [22]:
c = np.hstack((a, b))
print(c)

[[   0    1    2    3 -999 -999 -999 -999]
 [   4    5    6    7 -999 -999 -999 -999]
 [   8    9   10   11 -999 -999 -999 -999]
 [  12   13   14   15 -999 -999 -999 -999]
 [  16   17   18   19 -999 -999 -999 -999]]


In [ ]:
data = [1, 2, 4, 8]
a = np.exp(data)
print(a)
# exp(data)

[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03]


NameError: name 'exp' is not defined

In [43]:
a = np.random.rand(4)
b = np.random.randn(4, 3)
c = np.ones((1, 4), dtype=np.int32) * 4
print(a)
print(b)
print(c)

[0.78832026 0.82551991 0.41874842 0.34664062]
[[ 1.5651817   1.10770306  1.05051246]
 [ 0.12551215 -1.08067781  2.49676068]
 [ 1.12912717  0.42516147 -1.55045764]
 [ 2.69374962 -0.37506341 -0.77476434]]
[[4 4 4 4]]


In [45]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(4, 3)
(1, 4)


In [52]:
print(a + b.T)
print(b + c.T)
print(b.T + c)

[[ 2.35350196  0.95103206  1.5478756   3.04039024]
 [ 1.89602333 -0.2551579   0.84390989 -0.0284228 ]
 [ 1.83883273  3.32228059 -1.13170921 -0.42812373]]
[[5.5651817  5.10770306 5.05051246]
 [4.12551215 2.91932219 6.49676068]
 [5.12912717 4.42516147 2.44954236]
 [6.69374962 3.62493659 3.22523566]]
[[5.5651817  4.12551215 5.12912717 6.69374962]
 [5.10770306 2.91932219 4.42516147 3.62493659]
 [5.05051246 6.49676068 2.44954236 3.22523566]]


In [54]:
a = np.linspace(0, 1, 11)
b = np.arange(0, 1.1, 0.1)
print(a)
print(b)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [69]:
a = np.ones((5, 5)) * np.arange(-2, 3)

print(a)

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


In [77]:
# np.random.seed(10)
rng = np.random.default_rng(seed=10)
# b = np.random.randint(-5, 6, size=(5, 5))
a = a - rng.integers(-5, 6, size=(5, 5))

print(a)

[[-3. -5.  3.  4. -1.]
 [-4.  0.  4. -3.  2.]
 [ 4.  4.  1. -1.  3.]
 [-4.  5.  1.  1. -3.]
 [ 3. -4.  5.  3. -1.]]


In [78]:
a[a < 0] = 0
print(a)

[[0. 0. 3. 4. 0.]
 [0. 0. 4. 0. 2.]
 [4. 4. 1. 0. 3.]
 [0. 5. 1. 1. 0.]
 [3. 0. 5. 3. 0.]]


In [91]:
p = np.arange(1, 6).reshape((1, 5))
t = np.tile(p, (2, 2))
p[0,0] = 42
print(t)

[[1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]]


In [97]:
p = np.arange(1, 7).reshape((1, 2, -1))
print(p.repeat(2, axis=0))
print()
print(p.repeat(3, axis=1))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [4 5 6]
  [4 5 6]
  [4 5 6]]]


In [98]:
a = np.array([84, 91, 13, 65, 8, 31, 48, 4])
print(f'max value index : {a.argmax()}')
print(f'min value index : {a.argmin()}')

max value index : 1
min value index : 7


In [111]:
a = np.random.randint(-100, 101, size=(10000000,))
# a = -100 + 200 * np.random.rand(10000000)
print(a.min())
print(a.max())
print(a.mean())
print(a.std())

-100
100
-0.006209
58.0181137184614


In [116]:
a = np.random.normal(5, 2, size=(10000000,))
print(a.min())
print(a.max())
print(a.mean())
print(a.std())

-6.189020682446863
14.703528019189637
4.999526922068847
2.000619063251266


In [118]:
a = [[4, 1],
     [2, 4]]
b = [[5, 6],
     [1, 8]]

na = np.array(a)
nb = np.array(b)
print((na @ nb) @ (nb @ na))

[[1312 1665]
 [1328 1858]]


In [126]:
c = [[1, 2],
     [8, 4],
     [3, 9]]
nc = np.array(c)

print(na.shape)
print(nc.shape)
print(nb.shape)

print((nc @ na) + (nc @ nb))

(2, 2)
(3, 2)
(2, 2)
[[ 15  31]
 [ 84 104]
 [ 54 129]]


In [136]:
k = np.ones((3, 4)) * np.linspace(-1, 2.5, 4)
print(k)

print(np.ceil(k))
print(np.floor(k))
print(np.round(k))

[[-1.          0.16666667  1.33333333  2.5       ]
 [-1.          0.16666667  1.33333333  2.5       ]
 [-1.          0.16666667  1.33333333  2.5       ]]
[[-1.  1.  2.  3.]
 [-1.  1.  2.  3.]
 [-1.  1.  2.  3.]]
[[-1.  0.  1.  2.]
 [-1.  0.  1.  2.]
 [-1.  0.  1.  2.]]
[[-1.  0.  1.  2.]
 [-1.  0.  1.  2.]
 [-1.  0.  1.  2.]]


In [144]:
print(np.sum(k,axis=0))
print(np.cumsum(k,axis=0))

[-3.   0.5  4.   7.5]
[[-1.          0.16666667  1.33333333  2.5       ]
 [-2.          0.33333333  2.66666667  5.        ]
 [-3.          0.5         4.          7.5       ]]


In [151]:
random_value = np.array([13, 20, 28, 38, 14, 41, 0, 37])
random_value = random_value[np.newaxis,:].T
print(random_value)

[[13]
 [20]
 [28]
 [38]
 [14]
 [41]
 [ 0]
 [37]]


In [166]:
print(np.sort(random_value, axis=0))
indices = np.argsort(random_value, axis=0)
# indices = indices.reshape((indices.shape[0],))
print(random_value[indices].squeeze(axis=1))

[[ 0]
 [13]
 [14]
 [20]
 [28]
 [37]
 [38]
 [41]]
[[ 0]
 [13]
 [14]
 [20]
 [28]
 [37]
 [38]
 [41]]
